title: Cyber HackPath
description: "Tu Inicio en el Mundo del Hacking y la Ciberseguridad"
author:
  name: "WilL"
  #email: "someone@somewebsite.somedomain"
  url: "https://willeonardo19.github.io/cyber/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "WilL"
year : "2023"

google_analytics: G-VQFMX46E9C